version: "3.9"
services:
  postgres:
    image: postgres:latest
    volumes:
     - ./data:/var/lib/postgres
    environment:
      POSTGRES_DB: "POSTGRES_USER"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"